@startuml
class com.gaohongsen.MainWindow {
+ {static} CardLayout cardLayout
+ {static} JPanel contentPane
+ {static} User user
+ {static} boolean onlineState
+ {static} void main(String[])
}
class com.gaohongsen.AlterPanel {
+ Delivery inquireDelivery(int)
+ Delivery deleteDelivery(int)
+ Delivery alterDelivery(int,String,String,String,String,int)
}
class com.gaohongsen.Delivery {
- int id
- String sendPlace
- String receivePlace
- String sender
- String receiver
- int situation
+ int getId()
+ String getSendPlace()
+ String getReceivePlace()
+ String getSender()
+ String getReceiver()
+ int getSituation()
+ String getSituationString()
}
class com.gaohongsen.WelcomePanel {
+ User exitCheck(String)
}
class com.gaohongsen.Log {
- int id
- String name
- String account
- String datetime
- int type
+ int getId()
+ String getName()
+ String getAccount()
+ String getDatetime()
+ int getType()
+ String getTypeString()
}
class com.gaohongsen.LoginPanel {
+ {static} String verifyCode
+ User loginCheck(String,String)
+ void changeVerify(JLabel)
}
class com.gaohongsen.DeliveryListPanel {
+ Vector<Delivery> displayDelivery(int)
+ void exportExcel(int)
+ void addLine(int,Vector<Delivery>,Vector<Vector<Object>>)
}
class com.gaohongsen.PasswordChange {
+ User passwordChangeCheck(String,String,String)
}
class com.gaohongsen.Request {
- int type
- Object item
+ int getType()
+ Object getItem()
}
class com.gaohongsen.LogPanel {
+ Vector<Log> displayLog(int)
+ void exportExcel(int)
+ void addLine(int,Vector<Log>,Vector<Vector<Object>>)
}
class com.gaohongsen.Server {
+ {static} void main(String[])
}
class com.gaohongsen.Handler {
~ Socket sock
~ ObjectInputStream ois
~ ObjectOutputStream oos
+ void run()
- void handle(InputStream,OutputStream)
}
class com.gaohongsen.NewPanel {
+ Delivery newDelivery(String,String,String,String,int)
}
class com.gaohongsen.RegisterPanel {
+ {static} String verifyCode
+ User registerCheck(String,String,String,int)
+ {static} boolean passwordMatches(char[],char[])
+ void changeVerify(JLabel)
}
class com.gaohongsen.Reply {
- boolean hasSucceed
- Object item
+ boolean hasSucceed()
+ Object getItem()
}
class com.gaohongsen.Client {
~ {static} Socket sock
~ {static} boolean isInitialized
~ {static} ObjectOutputStream oos
~ {static} ObjectInputStream ois
+ {static} Object sendRequest(Request)
- {static} void initialize()
- {static} void disconnected()
- {static} Reply handle(Request)
}
class com.gaohongsen.User {
- int id
- String account
- String password
- String updatedPassword
- String name
- int permission
+ int getId()
+ String getAccount()
+ String getPassword()
+ String getUpdatedPassword()
+ String getName()
+ int getPermission()
+ String getPermissionString()
}
class com.gaohongsen.Database {
- {static} HikariConfig config
- {static} DataSource ds
- {static} boolean hasInitialized
- {static} void initialize()
+ {static} String getUserName(User)
+ {static} User getUserInfo(User)
+ {static} void addUser(User)
+ {static} void passwordCheck(User)
+ {static} void addLog(User,int)
+ {static} void updatePassword(User)
+ {static} Delivery addDelivery(Delivery)
+ {static} Delivery getDeliveryInfo(Delivery)
+ {static} void updateDelivery(Delivery)
+ {static} void deleteDelivery(Delivery)
+ {static} Vector<Delivery> displayDeliveries()
+ {static} Vector<Log> displayLogs()
+ {static} void outputDeliveries()
+ {static} void outputLogs()
}
class com.gaohongsen.ImgVerifyCode {
- int weight
- int height
- String text
- Random r
- String[] fontNames
- String codes
- Color randomColor()
- Font randomFont()
- char randomChar()
- void drawLine(BufferedImage)
- BufferedImage createImage()
+ BufferedImage getImage()
+ String getText()
+ {static} void output(BufferedImage,OutputStream)
}


com.gaohongsen.JFrame <|-- com.gaohongsen.MainWindow
com.gaohongsen.JPanel <|-- com.gaohongsen.AlterPanel
com.gaohongsen.Serializable <|.. com.gaohongsen.Delivery
com.gaohongsen.JPanel <|-- com.gaohongsen.WelcomePanel
com.gaohongsen.Serializable <|.. com.gaohongsen.Log
com.gaohongsen.JPanel <|-- com.gaohongsen.LoginPanel
com.gaohongsen.JPanel <|-- com.gaohongsen.DeliveryListPanel
com.gaohongsen.JFrame <|-- com.gaohongsen.PasswordChange
com.gaohongsen.Serializable <|.. com.gaohongsen.Request
com.gaohongsen.JPanel <|-- com.gaohongsen.LogPanel
com.gaohongsen.Thread <|-- com.gaohongsen.Handler
com.gaohongsen.JPanel <|-- com.gaohongsen.NewPanel
com.gaohongsen.JPanel <|-- com.gaohongsen.RegisterPanel
com.gaohongsen.Serializable <|.. com.gaohongsen.Reply
com.gaohongsen.Serializable <|.. com.gaohongsen.User
@enduml